### ISSUE TITLE
macos release

### ISSUE THREAD

**Issue by xmsec** [Aloxaf/rbkcrack#2]
release 可以放一下 macos 的吗 ..

**Comment by Aloxaf** [comment]
唔...有道理

**Comment by xmsec** [comment]
因为半个月前编译了一版 .. 发现又更新了

**Comment by Aloxaf** [comment]
已增加, 麻烦确认一下能否正常工作
(macOS 的交叉编译真麻烦



> 因为半个月前编译了一版 .. 发现又更新了

没事, 下次更新就不知道是什么时候了 (

**Comment by xmsec** [comment]
可以正常使用
