### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by sls463** [Aloxaf/rbkcrack#83]
我安装了Python 3.7，也安装了 Rust（rustup-init x64.exe），但安装  RUSTFLAGS='-C target_cpu=native' cargo install --git https://github.com/Aloxaf/rbkcrack 时显示 SyntaxError: invalid syntax ，由于不太会玩Python，百度也查不到答案，实在没折了，请求帮忙看看能否找出以下压缩密码，谢谢

en.zip   <---待破解的汉化语言文件压缩包
en - 副本.zip   <---原英文语言文件压缩包 (可做为明文来源，我选translation.json来做)
tr2.zip   <---我尝试制作的至少12字节的连续明文.zip (用en - 副本.zip中的translation.json来做的，不知有没做对，文件名改为translation2.json对应加密en.zip中的translation.json)
[en.zip](https://github.com/Aloxaf/rbkcrack/files/7574733/en.zip)
[en - 副本.zip](https://github.com/Aloxaf/rbkcrack/files/7574734/en.-.zip)
[tr2.zip](https://github.com/Aloxaf/rbkcrack/files/7574735/tr2.zip)

**Comment by Aloxaf** [comment]
1. 这玩意儿和 Python 没有关系，你安装完 Rust 后直接打开 CMD 然后执行  `cargo install --git https://github.com/Aloxaf/rbkcrack` 即可
2. translation.json 在两个压缩包中并不一样，一样的是 translation_old.json
3. 这个加密压缩包使用的压缩算法是 `Store`，你构建明文压缩包时也要使用同样的压缩算法（其实就是不压缩，仅归档）


解密后的：[en.zip](https://github.com/Aloxaf/rbkcrack/files/7575730/en.zip)

**Comment by sls463** [comment]
非常感谢！！！
1、原来是在CMD窗口下执行那条命令呀，怪不得我在Python窗口下执行提示出错；我在CMD尝试了一下，出现以下截图中的错误(Win10已验证并修复，第二次执行那条命令还是这个错误)，看提示难道我还得安装VS 201*软件吗？(好象VS满巨大的)
![CMD提示出错](https://user-images.githubusercontent.com/41649803/142758011-94a3ae22-86c7-4489-b6b1-68aea054479d.jpg)

2、translation.json 在两个压缩包中并不一样，一样的是 translation_old.json <---判断方法是根据原始大小是否一样对吗？如果三个文件的原始大小都不一样，那么我尝试制作的那个至少12字节的连续明文.zip的方法是否正确？(当然压缩算法得改为 Store)

3、这个刚学会了^_^

**Comment by Aloxaf** [comment]
> 非常感谢！！！ 1、原来是在CMD窗口下执行那条命令呀，怪不得我在Python窗口下执行提示出错；我在CMD尝试了一下，出现以下截图中的错误(Win10已验证并修复，第二次执行那条命令还是这个错误)，看提示难道我还得安装VS 201*软件吗？(好象VS满巨大的) ![CMD提示出错](https://user-images.githubusercontent.com/41649803/142758011-94a3ae22-86c7-4489-b6b1-68aea054479d.jpg)

你可以直接在 https://github.com/Aloxaf/rbkcrack/releases 下载预编译版本

> 2、translation.json 在两个压缩包中并不一样，一样的是 translation_old.json <---判断方法是根据原始大小是否一样对吗？如果三个文件的原始大小都不一样，那么我尝试制作的那个至少12字节的连续明文.zip的方法是否正确？(当然压缩算法得改为 Store)

判断依据是文件的 CRC32 是否一致
